### ISSUE TITLE
unable to install blender addon using 'C'

### ISSUE THREAD

**Issue by LASTWINDOW** [AxioDL/PathShagged#11]
I'm having the same problem Morningshadows had with the program. I installed Blender (2.76b), already had MSVC 2015 CRT installed and a PAL iso of Metroid Prime that works fine with Dolphin (GM8P01 and 694e7ceeaaa3cd68c693f1d2e4b4f48a). I'm using Windows 10.

After using the command line _hecl extract "Metroid Prime.iso"_ it tells me what's about to get exported and then tries to establish connection with Blender, but fails when it's about to install the blender addon.

![blender_addon_issue](https://cloud.githubusercontent.com/assets/16897955/12695800/21022230-c759-11e5-9046-b808843f4110.png)

**Comment by Antidote** [comment]
Could have sworn we fixed that, are you sure you're using the latest prototype release?

**Comment by LASTWINDOW** [comment]
I'm using the latest precompiled build.

**Comment by Antidote** [comment]
Please try this test build
[Prototype 7](https://www.dropbox.com/s/pw4vthg601v02yq/p7.zip?dl=0)

**Comment by LASTWINDOW** [comment]
It tells me I'm missing ucrtbased.dll, VCRUNTIME140D.dll and MSVCP140D.dll.

**Comment by Antidote** [comment]
gah!, whoops! sorry about that.

**Comment by Antidote** [comment]
Ok, sorry for the wait, had to run to the store, but go ahead and try the same link I provided, I've updated it with a release build. Please report if the plugin installs, and if you're able to extract the whole game.

**Comment by LASTWINDOW** [comment]
Don't worry, it's nothing. It was already kinda late for me anyway.

It seems to be working fine, but it's taking some time. 98% on Metroid3.pak right now. I'll report again once it finishes the extraction.

**Comment by Antidote** [comment]
It can take 4 or more hours to completely extract.

**Comment by LASTWINDOW** [comment]
Alright. Extracted everything without errors, tried a couple of areas and they looked fine.

Thanks! You can close this issue.
