### ISSUE TITLE
Unable to extract MP2, fatal error during FrontEnd.pak

### ISSUE THREAD

**Issue by TheEnemyCube** [AxioDL/PathShagged#5]
As title says, during AudioGrp.pak, the error "[Fatal Error BlenderConnection] error sending 'bpy.types.Material.retro_depth_sort = bpy.props.BoolProperty(name='Retro: Transparent Depth Sort')' to blender" causes hecl to crash. When I attempt to put python output into a log.txt, I get:

Initialized project at 'E:\MetroidExtractor\MetroidPrime2\rtc-mp2/.hecl
Constructed tool 'extract' 2

After this nothing happens until I press enter again and then I get two instances of:

AL lib: <EE> UpdateDeviceParams: Failed to set 44100hz, got 48000hz instead

An MD5 of ce781ad1452311ca86667cf8dbd7d112 was acquired from my image.

Blender version is 2.76, running Windows 7 x64

**Comment by Antidote** [comment]
Thank you for the report, We'll see what's going on and see about fixing it. Also that AL bug is rather strange, and should be unrelated to what we're using blender for.

**Comment by 7imekeeper** [comment]
So I am getting the same error, however I was able to somewhat pipe the output into a log file. Upon doing so the crash no longer happens but the log file produced seems corrupt somehow. The first 500 lines or so seem normal but after that there is really odd behavior. Notepad++ doesn't seem to display correctly but opening it in normal Notepad apparently allows me to see the full contents.

The last normal lines of output are:
"Continue? (Y/n) 
Using DataSpec MP1:
  Update Partition"

After that there are about 10 blank lines and then the remainder of the file is filled up with dash characters.

Hopefully you can do something with this information.

Blender version 2.76b, running Windows 8.1

**Comment by Antidote** [comment]
Hmmmmmm, that's the same error I was able to reproduce once, but haven't had any luck with since.

Can you run it in verbose mode? -vv or -vvv should work.

**Comment by 7imekeeper** [comment]
Ok so if I don't try to write to a file I'm able to see a bit more than was in my log. Here's a pastebin: http://pastebin.com/zfHBpzJ2

Also, as a heads up, I'm using the release exe that you guys have provided (looks like 25 days ago was last release) and am not compiling the current source.

**Comment by Antidote** [comment]
AH HA!, Unicode!!!!

**Comment by Antidote** [comment]
Hmm, I'm curious, can you move it into a path that does not have spaces and try again?

**Comment by 7imekeeper** [comment]
Same issue. Still says there is a unicode error.

**Comment by Antidote** [comment]
Yeah, we kind of figured it wasn't a spacing issue, but it didn't hurt to try.

**Comment by Antidote** [comment]
Alright, we traced the issue down, we should have a working fix here in a bit.
But for now an explanation is in order:
Currently we're not escaping or transforming path separators, so when "C:\Users\*" is being passed to python it's seeing \Users as a unicode escape, causing this issue:
http://stackoverflow.com/questions/18084554/why-do-i-get-a-syntaxerror-for-a-unicode-escape-in-my-file-path

A simple fix by all means, but still an irritating one.

**Comment by jackoalan** [comment]
Found it myself.. extracted to `D:\Umos` and the issue occurred early on.

Updated the release to p6e:
https://github.com/AxioDL/PathShagged/releases

Let us know if that works for you!

**Comment by 7imekeeper** [comment]
Currently testing. Its made it past where it was crashing before and working great so far!

**Comment by Antidote** [comment]
Nice, let us know if you get get a full extract, depending on your computer it can take anywhere from 2 to 4 hours, sometimes longer.

**Comment by 7imekeeper** [comment]
Full Extraction seems to be coming along nicely. Several of the paks have been extracted at this point!

I do have a question though. Is collision data extracted as well? I haven't seen any hints of it yet.

**Comment by Antidote** [comment]
Yes, collision data is stored in layer 2 for Maps, we currently don't export DCLN, but we will soon.

**Comment by 7imekeeper** [comment]
Everything extracted nicely!

**Comment by Antidote** [comment]
Nice!
