### ISSUE TITLE
"unable to install blender addon using,'C'", and,"unexpected PAK magic" Help?

### ISSUE THREAD

**Issue by Morningshadows** [AxioDL/PathShagged#6]
Just freshly downloaded everything I need to get going with extracting, and whenever I attempt to extract any .iso, I get one of the two messages above. The first message comes after hitting y to go forward with the extraction, and the other one appears as soon as I attempt to extract certain .iso's. Any idea how I can fix this? I'm probably just doing something obviously wrong, I'm just new to this is all.

**Comment by jackoalan** [comment]
Thanks for the report!
We'll see what we can do to address the particulars of your system and image.

Just a few questions first:
* Which Game ID are you attempting to extract? (GM8E01, R3ME01, etc...)?
* Have you installed blender 2.76+?
* Which version of Windows?

Also, 'C' should actually be the full path of the blender addon out, but I just discovered a bug on the Windows version that truncates it down to just the first character.. I've prepared a fix for the next release thanks to your report.

**Comment by Antidote** [comment]
Please post the MD5 of the image you're using as well, that will help us verify that you're using a known good image.

**Comment by Morningshadows** [comment]
R3ME01, I do have Blender 2.76, and the version is Windows 8.1.

As for the MD5, I'm a little confused... (Again, completely new to this, so please be patient) What do you mean by the image? As in, just the file itself? At this point, I would assume not, because I wasn't able to find Info or MD5 Sum. Again, sorry for the confusion. Still learning~

**Comment by Morningshadows** [comment]
I've also tried an .iso that has the complete trilogy in it, not just separated into segments, and I've gotten the same results.

**Comment by jackoalan** [comment]
Image means the .iso, as in a CD/DVD image.

Dolphin is a GameCube/Wii emulator with a built-in MD5 calculator for game images.  MD5 a way of verifying that an image file is valid. You compare the computed MD5 number (hash) against a known-good one. Alternatively, you can use a general utility like HashTab to compute this from your image.

My R3ME01 has an MD5 of **823df1c3c425f1383529f368f6479359**; make sure yours matches this one. If not, you may have a bad dump.

**Comment by Antidote** [comment]
Due to lack of activity I will be closing this issue as invalid in 3 days, if this issue still persists please respond with the relevant information.

**Comment by Antidote** [comment]
3 days have passed, I'm now closing this issue as invalid, if this issue still persists, create another issue with the relevant information.
